### ISSUE TITLE
Any plans for the next release?

### ISSUE THREAD

**Issue by mkmn** [StudistCorporation/scimaenaga#39]
Hello!
Thank you for always maintaining this gem.

I noticed that support for Ruby 3.1 and 3.2 was merged. ( https://github.com/StudistCorporation/scimaenaga/pull/38 )
I also would like to utilize this update, but do you have any plans for the next release?

I look forward to the release of a new version.

**Comment by mtakeda15** [comment]
Sorry for the late reply.
We've already released it on Apr 27.

https://github.com/StudistCorporation/scimaenaga/releases/tag/v0.9.3
